args_from_exp_name: null
args_path: null
batch_size: 4
bbox_num_kpts: 8
belief_hidden_dim: 256
belief_num_layers: 2
ckpt_exp_name: null
ckpt_path: null
comet_exp_name: null
cvae_kl_loss_coef: 1.0
cvae_num_samples: 256
cvae_z_dim: 256
device: cuda
dino_features_folder_name: null
do_chunkify_val: false
do_debug: false
do_freeze_encoders: false
do_ignore_file_args_with_provided: true
do_load_session: false
do_log_every_seq: false
do_log_every_ts: false
do_overfit: false
do_perturb_init_gt_for_rel_pose: false
do_predict_2d_t: false
do_predict_3d_rot: false
do_predict_6d_rot: true
do_predict_abs_pose: false
do_predict_kpts: false
do_predict_rel_pose: false
do_preload_ds: false
do_print_seq_stats: false
do_profile: false
do_save_artifacts: true
do_split_train_for_val: false
do_subtract_bg: false
do_upload_histograms: false
do_vis: true
dropout: 0.0
dropout_heads: 0.0
ds_alias: cube_scaled_1k_random_multiobj
ds_folder_name_train: custom_sim_cube_scaled_1k_random_multiobj
ds_folder_name_val: custom_sim_cube_scaled_1k_random_multiobj_val
ds_name: ikea_multiobj
ds_types:
- train
- val
encoder_depth_weights: imagenet
encoder_img_weights: imagenet
encoder_name: resnet50
encoder_out_dim: 512
end_frame_idx: 100
es_delta: 0.0
es_patience_epochs: 60
exp_disabled: false
exp_name: cube_scaled_1k_random_multiobj_memotr_continue_exp_null
exp_tags: []
factors: null
help: ==SUPPRESS==
hidden_dim: 256
ignored_file_args: []
include_abs_pose_loss_for_rel: false
lr: 0.0002
lr_encoders: 2.0e-05
lr_scaler: null
lrs_delta: 0.0
lrs_gamma: 0.5
lrs_min_lr: 1.0e-06
lrs_patience: 30
lrs_step_size: 10
lrs_threshold_mode: abs
lrs_type: pl
mask_pixels_prob: 0.1
max_clip_grad_norm: 0.1
max_random_seq_step: 4
max_train_videos: 10000
max_val_videos: 24
model_name: memotr
mt_d_model: 256
mt_do_calibrate_kpt: false
mt_do_refinement: false
mt_do_refinement_with_attn: false
mt_do_refinement_with_pose_token: false
mt_encoding_type: spatial
mt_kpt_spatial_dim: 2
mt_n_heads: 8
mt_n_layers: 6
mt_n_tokens: 300
mt_num_queries: 5
mt_roi_feature_dim: 512
mt_uncertainty_coef: 0.1
mt_use_depth: false
mt_use_mask_on_input: false
mt_use_pose_tokens: false
mt_use_roi: false
norm_layer_type: frozen_bn
num_classes: 1
num_epochs: 300
num_samples: 10
num_workers: 4
obj_names: []
obj_names_val: []
opt_only:
- rot
- t
- labels
- boxes
- depth
pose_loss_name: separate
r_num_layers_inc: 0
rnn_state_init_type: zeros
rnn_type: gru
rot_loss_name: mse
rot_out_dim: 6
rot_repr: rotation6d
rt_hidden_dim: 384
rt_mlps_num_layers: 3
save_epoch_freq: 4
seed: 10
seq_len: 5
seq_len_max_train: 100
seq_start: null
seq_step: 1
state_dim: 512
t_loss_name: mse
t_out_dim: 3
t_repr: 3d
target_hw: null
tf_bbox_loss_coef: 1.0
tf_ce_loss_coef: 2.0
tf_depth_loss_coef: 1
tf_do_merge_frame_features: false
tf_giou_loss_coef: 1.0
tf_rot_loss_coef: 1.0
tf_t_loss_coef: 1.0
tf_track_query_false_negative_prob: 0.4
tf_track_query_false_positive_prob: 0.1
tf_transformer_hidden_dim: 288
tf_use_box_refine: false
tf_use_dab: false
tf_use_deformable: false
tf_use_focal_loss: true
tf_use_kpts: false
tf_use_kpts_as_img: false
tf_use_kpts_as_ref_pt: false
tf_use_multi_frame_encoding: false
tf_use_pretrained_model: true
transform_names:
- brightness
- motion_blur
- gamma
- iso
transform_prob: 0.8
use_allocentric_pose: false
use_belief_decoder: false
use_crop_for_rot: false
use_cuda: true
use_ddp: true
use_depth: false
use_entire_seq_in_train: false
use_es: true
use_es_train: false
use_es_val: true
use_factors: false
use_kpts_for_rot: false
use_lrs: false
use_mask_for_bbox_2d: false
use_mlp_for_prev_pose: false
use_obs_belief: false
use_pnp_for_rot_pred: false
use_prev_latent: false
use_prev_pose_condition: false
use_priv_decoder: false
use_rnn: true
use_seq_len_curriculum: false
use_test_set: false
val_epoch_freq: 2
val_split_share: 0.1
vis_epoch_freq: 50
weight_decay: 0.0001
